apiVersion: v1
kind: Secret
metadata:
  name: {{ include "userlist.fullname" . }}-secret
type: Opaque
data:
  POSTGRES_USER: "{{ .Values.image.db.user }}"
  POSTGRES_PASSWORD: "{{ .Values.image.db.password }}"   